manifest:
  remotes:
    - name: pseudocc
      url-base: https://github.com/pseudocc
  projects:
    - name: zmk
      remote: pseudocc
      revision: main
      import: app/west.yml
  self:
    path: config
